server:
  port: 8090
  use-forward-headers: true
  undertow:
    io-threads: 2
    worker-threads: 36
    buffer-size: 1024
    directBuffers: true
#spring
spring:
  devtools:
    restart:
      enabled: true

  # H2DATABASE配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:/db/schema-h2.sql
    data: classpath:/db/data-h2.sql
    url: jdbc:h2:file:~/test/test
    username: root
    password: 123456
    platform: h2
    initialization-mode: always
    continue-on-error: true
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true

    #MySql配置
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://47.95.210.109:3306/viewer?characterEncoding=utf8&useSSL=false
#    username: root
#    password: 123456

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.aikefu.entity.domain
  typeEnumsPackage: com.aikefu.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  file: ./logs/log.log


